# frozen_string_literal: true

source "https://rubygems.org"

git_source(:gitlab) {|repo_name| "https://gitlab.com/safetypanda/novifc_sourcecode" }

gem 'discordrb'
gem 'streamio-ffmpeg'
gem 'opus-ruby'
gem 'configatron'

gem 'xivapi', :git => 'https://github.com/xivapi/xivapi-ruby.git', :tag => 'v0.3.1'
